# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
# ', name:'Cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
# ', name:'Mayor.create(name: 'Emanuel', city: cities.first)

puts 'SETTING UP SPORTS'
Sport.delete_all
football = Sport.create(name:"Football");
soccer = Sport.create(name:"Soccer");
baseball = Sport.create(name:"Baseball");
basketball = Sport.create(name:"Basketball");

puts 'SETTING UP LEAGUES'
League.delete_all
League.create([
  {name: 'NFL', sport_id:football.id},
  {name: 'NCAA Football', sport_id:football.id},
  {name: 'NBA', sport_id:basketball.id},
  {name: 'MLB', sport_id:baseball.id},
  {name: 'MLS', sport_id:soccer.id}
]);

puts 'SETTING UP STATES'
State.delete_all
puts 'Deleted existing states'
State.create([ 
  { name:'Alabama', abbreviation:'AL' },
  { name:'Alaska', abbreviation:'AK' },
  { name:'Arizona', abbreviation:'AZ' },
  { name:'Arkansas', abbreviation:'AR' },
  { name:'California', abbreviation:'CA' },
  { name:'Colorado', abbreviation:'CO' },
  { name:'Connecticut', abbreviation:'CT' },
  { name:'Delaware', abbreviation:'DE' },
  { name:'Florida', abbreviation:'FL' },
  { name:'Georgia', abbreviation:'GA' },
  { name:'Hawaii', abbreviation:'HI' },
  { name:'Idaho', abbreviation:'ID' },
  { name:'Illinois', abbreviation:'IL' },
  { name:'Indiana', abbreviation:'IN' },
  { name:'Iowa', abbreviation:'IA' },
  { name:'Kansas', abbreviation:'KS' },
  { name:'Kentucky', abbreviation:'KY' },
  { name:'Louisiana', abbreviation:'LA' },
  { name:'Maine', abbreviation:'ME' },
  { name:'Maryland', abbreviation:'MD' },
  { name:'Massachusetts', abbreviation:'MA' },
  { name:'Michigan', abbreviation:'MI' },
  { name:'Minnesota', abbreviation:'MN' },
  { name:'Mississippi', abbreviation:'MS' },
  { name:'Missouri', abbreviation:'MO' },
  { name:'Montana', abbreviation:'MT' },
  { name:'Nebraska', abbreviation:'NE' },
  { name:'Nevada', abbreviation:'NV' },
  { name:'New Hampshire', abbreviation:'NH' },
  { name:'New Jersey', abbreviation:'NJ' },
  { name:'New Mexico', abbreviation:'NM' },
  { name:'New York', abbreviation:'NY' },
  { name:'North Carolina', abbreviation:'NC' },
  { name:'North Dakota', abbreviation:'ND' },
  { name:'Ohio', abbreviation:'OH' },
  { name:'Oklahoma', abbreviation:'OK' },
  { name:'Oregon', abbreviation:'OR' },
  { name:'Pennsylvania', abbreviation:'PA' },
  { name:'Rhode Island', abbreviation:'RI' },
  { name:'South Carolina', abbreviation:'SC' },
  { name:'South Dakota', abbreviation:'SD' },
  { name:'Tennessee', abbreviation:'TN' },
  { name:'Texas', abbreviation:'TX' },
  { name:'Utah', abbreviation:'UT' },
  { name:'Vermont', abbreviation:'VT' },
  { name:'Virginia', abbreviation:'VA' },
  { name:'Washington', abbreviation:'WA' },
  { name:'West Virginia', abbreviation:'WV' },
  { name:'Wisconsin', abbreviation:'WI' },
  { name:'Wyoming', abbreviation:'WY' },
  { name:'American Samoa', abbreviation:'AS' },
  { name:'District of Columbia', abbreviation:'DC' },
  { name:'Federated States of Micronesia', abbreviation:'FM' },
  { name:'Guam', abbreviation:'GU' },
  { name:'Marshall Islands', abbreviation:'MH' },
  { name:'Northern Mariana Islands', abbreviation:'MP' },
  { name:'Palau', abbreviation:'PW' },
  { name:'Puerto Rico', abbreviation:'PR' },
  { name:'Virgin Islands', abbreviation:'VI' },
  { name:'Armed Forces Africa', abbreviation:'AE' },
  { name:'Armed Forces Americas', abbreviation:'AA' },
  { name:'Armed Forces Canada', abbreviation:'AE' },
  { name:'Armed Forces Europe', abbreviation:'AE' },
  { name:'Armed Forces Middle East', abbreviation:'AE' },
  { name:'Armed Forces Pacific', abbreviation:'AP' }
])
puts 'States created'

puts 'SETTING UP COUNTRIES'
Country.delete_all
puts 'Deleted existing countries'
Country.create([ 
  { abbreviation:'US', name:'United States' },  
  { abbreviation:'CA', name:'Canada' },
  { abbreviation:'UK', name:'United Kingdom' },   
  { abbreviation:'IE', name:'Ireland' },
  { abbreviation:'AU', name:'Australia' }, 
  { abbreviation:'NZ', name:'New Zealand' },   
  { abbreviation:'ZA', name:'South Africa' },  

  { abbreviation:'AT', name:'Austria' },  
  { abbreviation:'BE', name:'Belgium' },
  { abbreviation:'DK', name:'Denmark' },
  { abbreviation:'FR', name:'France' },
  { abbreviation:'DE', name:'Germany' },
  { abbreviation:'GR', name:'Greece' },
  { abbreviation:'IT', name:'Italy' },
  { abbreviation:'MX', name:'Mexico' },
  { abbreviation:'NL', name:'Netherlands' },   
  { abbreviation:'ES', name:'Spain' },   
    
  { abbreviation:'AF', name:'Afghanistan' },   
  { abbreviation:'AL', name:'Albania' },   
  { abbreviation:'DZ', name:'Algeria' },
  { abbreviation:'AS', name:'American Samoa' },   
  { abbreviation:'AD', name:'Andorra' }, 
  { abbreviation:'AO', name:'Angola' },   
  { abbreviation:'AI', name:'Anguilla' },
  { abbreviation:'AQ', name:'Antarctica' },   
  { abbreviation:'AG', name:'Antigua and Barbuda' },   
  { abbreviation:'AR', name:'Argentina' },   
  { abbreviation:'AM', name:'Armenia' },
  { abbreviation:'AW', name:'Aruba' }, 
  { abbreviation:'AZ', name:'Azerbaijan' },
  { abbreviation:'BS', name:'Bahamas' },  
  { abbreviation:'BH', name:'Bahrain' }, 
  { abbreviation:'BD', name:'Bangladesh' },
  { abbreviation:'BB', name:'Barbados' }, 
  { abbreviation:'BY', name:'Belarus' }, 
  { abbreviation:'BZ', name:'Belize' },
  { abbreviation:'BJ', name:'Benin' },
  { abbreviation:'BM', name:'Bermuda' },
  { abbreviation:'BT', name:'Bhutan' },
  { abbreviation:'BO', name:'Bolivia' },
  { abbreviation:'BA', name:'Bosnia and Herzegovina' },
  { abbreviation:'BW', name:'Botswana' },
  { abbreviation:'BV', name:'Bouvet Island' },
  { abbreviation:'BR', name:'Brazil' },
  { abbreviation:'IO', name:'British Indian Ocean Territory' },
  { abbreviation:'BN', name:'Brunei Darussalam' },
  { abbreviation:'BG', name:'Bulgaria' },
  { abbreviation:'BF', name:'Burkina Faso' },
  { abbreviation:'BI', name:'Burundi' },   
  { abbreviation:'KH', name:'Cambodia' }, 
  { abbreviation:'CM', name:'Cameroon' },
  { abbreviation:'CV', name:'Cape Verde' },
  { abbreviation:'KY', name:'Cayman Islands' },
  { abbreviation:'CF', name:'Central African Republic' },
  { abbreviation:'TD', name:'Chad' },
  { abbreviation:'CL', name:'Chile' },
  { abbreviation:'CN', name:'China' },
  { abbreviation:'CX', name:'Christmas Island' },
  { abbreviation:'CC', name:'Cocos (Keeling Islands)' },
  { abbreviation:'CO', name:'Colombia' },
  { abbreviation:'KM', name:'Comoros' },
  { abbreviation:'CG', name:'Congo' }, 
  { abbreviation:'CK', name:'Cook Islands' },
  { abbreviation:'CR', name:'Costa Rica' }, 
  { abbreviation:'CI', name:"Cote D'Ivoire (Ivory Coast)" },
  { abbreviation:'HR', name:'Croatia (Hrvatska)' },
  { abbreviation:'CU', name:'Cuba' },
  { abbreviation:'CY', name:'Cyprus' },
  { abbreviation:'CZ', name:'Czech Republic' },
  { abbreviation:'DJ', name:'Djibouti' },
  { abbreviation:'DM', name:'Dominica' },
  { abbreviation:'DO', name:'Dominican Republic' },
  { abbreviation:'TP', name:'East Timor' },
  { abbreviation:'EC', name:'Ecuador' },
  { abbreviation:'EG', name:'Egypt' }, 
  { abbreviation:'SV', name:'El Salvador' }, 
  { abbreviation:'GQ', name:'Equatorial Guinea' },  
  { abbreviation:'ER', name:'Eritrea' }, 
  { abbreviation:'EE', name:'Estonia' }, 
  { abbreviation:'ET', name:'Ethiopia' },
  { abbreviation:'FK', name:'Falkland Islands (Malvinas)' },
  { abbreviation:'FO', name:'Faroe Islands' }, 
  { abbreviation:'FJ', name:'Fiji' },
  { abbreviation:'FI', name:'Finland' },
  { abbreviation:'FX', name:'France, Metropolitan' },
  { abbreviation:'GF', name:'French Guiana' },
  { abbreviation:'PF', name:'French Polynesia' },
  { abbreviation:'TF', name:'French Southern Territories' },
  { abbreviation:'GA', name:'Gabon' },
  { abbreviation:'GM', name:'Gambia' },
  { abbreviation:'GE', name:'Georgia' },
  { abbreviation:'GH', name:'Ghana' },  
  { abbreviation:'GI', name:'Gibraltar' },
  { abbreviation:'GL', name:'Greenland' },
  { abbreviation:'GD', name:'Grenada' }, 
  { abbreviation:'GP', name:'Guadeloupe' },
  { abbreviation:'GU', name:'Guam' }, 
  { abbreviation:'GT', name:'Guatemala' },
  { abbreviation:'GN', name:'Guinea' },
  { abbreviation:'GW', name:'Guinea-Bissau' },
  { abbreviation:'GY', name:'Guyana' },
  { abbreviation:'HT', name:'Haiti' },
  { abbreviation:'HM', name:'Heard and McDonald Islands' },
  { abbreviation:'HN', name:'Honduras' },
  { abbreviation:'HK', name:'Hong Kong' },
  { abbreviation:'HU', name:'Hungary' },
  { abbreviation:'IS', name:'Iceland' },
  { abbreviation:'IN', name:'India' },
  { abbreviation:'ID', name:'Indonesia' },
  { abbreviation:'IR', name:'Iran' },
  { abbreviation:'IQ', name:'Iraq' },
  { abbreviation:'IL', name:'Israel' },
  { abbreviation:'JM', name:'Jamaica' },
  { abbreviation:'JP', name:'Japan' },
  { abbreviation:'JO', name:'Jordan' }, 
  { abbreviation:'KZ', name:'Kazakhstan' },
  { abbreviation:'KE', name:'Kenya' },
  { abbreviation:'KI', name:'Kiribati' },
  { abbreviation:'KP', name:'Korea (North)' },
  { abbreviation:'KR', name:'Korea (South)' },
  { abbreviation:'KW', name:'Kuwait' },   
  { abbreviation:'KG', name:'Kyrgyzstan' },
  { abbreviation:'LA', name:'Laos' },  
  { abbreviation:'LV', name:'Latvia' },   
  { abbreviation:'LB', name:'Lebanon' },   
  { abbreviation:'LS', name:'Lesotho' },  
  { abbreviation:'LR', name:'Liberia' }, 
  { abbreviation:'LY', name:'Libya' },   
  { abbreviation:'LI', name:'Liechtenstein' },   
  { abbreviation:'LT', name:'Lithuania' },   
  { abbreviation:'LU', name:'Luxembourg' }, 
  { abbreviation:'MO', name:'Macau' },   
  { abbreviation:'MK', name:'Macedonia' },   
  { abbreviation:'MG', name:'Madagascar' },   
  { abbreviation:'MW', name:'Malawi' },   
  { abbreviation:'MY', name:'Malaysia' },
  { abbreviation:'MV', name:'Maldives' },   
  { abbreviation:'ML', name:'Mali' },   
  { abbreviation:'MT', name:'Malta' },   
  { abbreviation:'MH', name:'Marshall Islands' },   
  { abbreviation:'MQ', name:'Martinique' },   
  { abbreviation:'MR', name:'Mauritania' },  
  { abbreviation:'MU', name:'Mauritius' },  
  { abbreviation:'YT', name:'Mayotte' },
  { abbreviation:'FM', name:'Micronesia' },   
  { abbreviation:'MD', name:'Moldova' },   
  { abbreviation:'MC', name:'Monaco' },   
  { abbreviation:'MN', name:'Mongolia' },
  { abbreviation:'MS', name:'Montserrat' },   
  { abbreviation:'MA', name:'Morocco' },   
  { abbreviation:'MZ', name:'Mozambique' },   
  { abbreviation:'MM', name:'Myanmar' },   
  { abbreviation:'NA', name:'Namibia' },  
  { abbreviation:'NR', name:'Nauru' },   
  { abbreviation:'NP', name:'Nepal' },  
  { abbreviation:'AN', name:'Netherlands Antilles' },   
  { abbreviation:'NC', name:'New Caledonia' },   
  { abbreviation:'NI', name:'Nicaragua' },   
  { abbreviation:'NE', name:'Niger' },   
  { abbreviation:'NG', name:'Nigeria' },
  { abbreviation:'NU', name:'Niue' },  
  { abbreviation:'NF', name:'Norfolk Island' },   
  { abbreviation:'MP', name:'Northern Mariana Islands' },   
  { abbreviation:'NO', name:'Norway' },   
  { abbreviation:'OM', name:'Oman' },   
  { abbreviation:'PK', name:'Pakistan' },   
  { abbreviation:'PW', name:'Palau' },   
  { abbreviation:'PA', name:'Panama' },   
  { abbreviation:'PG', name:'Papua New Guinea' },   
  { abbreviation:'PY', name:'Paraguay' },   
  { abbreviation:'PE', name:'Peru' },   
  { abbreviation:'PH', name:'Philippines' },   
  { abbreviation:'PN', name:'Pitcairn' },   
  { abbreviation:'PL', name:'Poland' },   
  { abbreviation:'PT', name:'Portugal' },   
  { abbreviation:'PR', name:'Puerto Rico' },   
  { abbreviation:'QA', name:'Qatar' },   
  { abbreviation:'RE', name:'Reunion' },
  { abbreviation:'RO', name:'Romania' },   
  { abbreviation:'RU', name:'Russian Federation' },   
  { abbreviation:'RW', name:'Rwanda' },   
  { abbreviation:'KN', name:'Saint Kitts and Nevis' },
  { abbreviation:'LC', name:'Saint Lucia' },  
  { abbreviation:'VC', name:'Saint Vincent and The Grenadines' },
  { abbreviation:'WS', name:'Samoa' },   
  { abbreviation:'SM', name:'San Marino' },   
  { abbreviation:'ST', name:'Sao Tome and Principe' }, 
  { abbreviation:'SA', name:'Saudi Arabia' },   
  { abbreviation:'SN', name:'Senegal' },   
  { abbreviation:'SC', name:'Seychelles' },   
  { abbreviation:'SL', name:'Sierra Leone' },
  { abbreviation:'SG', name:'Singapore' },   
  { abbreviation:'SK', name:'Slovak Republic' },   
  { abbreviation:'SI', name:'Slovenia' },   
  { abbreviation:'SB', name:'Solomon Islands' },   
  { abbreviation:'SO', name:'Somalia' },   
  { abbreviation:'GS', name:'S. Georgia and S. Sandwich Isls.' },  
  { abbreviation:'LK', name:'Sri Lanka' },   
  { abbreviation:'SH', name:'St. Helena' },   
  { abbreviation:'PM', name:'St. Pierre and Miquelon' },   
  { abbreviation:'SD', name:'Sudan' },   
  { abbreviation:'SR', name:'Suriname' },   
  { abbreviation:'SJ', name:'Svalbard and Jan Mayen Islands' },   
  { abbreviation:'SZ', name:'Swaziland' },   
  { abbreviation:'SE', name:'Sweden' },   
  { abbreviation:'CH', name:'Switzerland' },   
  { abbreviation:'SY', name:'Syria' },   
  { abbreviation:'TW', name:'Taiwan' },   
  { abbreviation:'TJ', name:'Tajikistan' },   
  { abbreviation:'TZ', name:'Tanzania' },   
  { abbreviation:'TH', name:'Thailand' },  
  { abbreviation:'TG', name:'Togo' },   
  { abbreviation:'TK', name:'Tokelau' },   
  { abbreviation:'TO', name:'Tonga' },   
  { abbreviation:'TT', name:'Trinidad and Tobago' },   
  { abbreviation:'TN', name:'Tunisia' },   
  { abbreviation:'TR', name:'Turkey' },   
  { abbreviation:'TM', name:'Turkmenistan' },   
  { abbreviation:'TC', name:'Turks and Caicos Islands' },   
  { abbreviation:'TV', name:'Tuvalu' },   
  { abbreviation:'UG', name:'Uganda' },  
  { abbreviation:'UA', name:'Ukraine' },
  { abbreviation:'AE', name:'United Arab Emirates' },
  { abbreviation:'UM', name:'US Minor Outlying Islands' },
  { abbreviation:'UY', name:'Uruguay' },   
  { abbreviation:'UZ', name:'Uzbekistanv' },   
  { abbreviation:'VU', name:'Vanuatu' },   
  { abbreviation:'VA', name:'Vatican City State (Holy See)' },   
  { abbreviation:'VE', name:'Venezuela' },   
  { abbreviation:'VN', name:'Viet Nam' },   
  { abbreviation:'VG', name:'Virgin Islands (British)' },   
  { abbreviation:'VI', name:'Virgin Islands (US)' },   
  { abbreviation:'WF', name:'Wallis and Futuna Islands' },   
  { abbreviation:'EH', name:'Western Sahara' },   
  { abbreviation:'YE', name:'Yemen' },   
  { abbreviation:'YU', name:'Yugoslavia' },   
  { abbreviation:'ZR', name:'Zaire' },   
  { abbreviation:'ZM', name:'Zambia' },   
  { abbreviation:'ZW', name:'Zimbabwe' }
])
puts "Countries created"
